-- Script para criar usuário no sistema de autenticação do Supabase
-- Execute este script no SQL Editor do Supabase Dashboard

-- Primeiro, vamos inserir o usuário diretamente na tabela auth.users
-- IMPORTANTE: Este script deve ser executado no Supabase Dashboard com privilégios de admin

INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    invited_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    recovery_sent_at,
    email_change_token_new,
    email_change,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'exattagestaocontabil@gmail.com',
    crypt('R@102030', gen_salt('bf')), -- Senha criptografada
    NOW(),
    NULL,
    '',
    NULL,
    '',
    NULL,
    '',
    '',
    NULL,
    NULL,
    '{"provider": "email", "providers": ["email"]}',
    '{}',
    FALSE,
    NOW(),
    NOW(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL
);

-- Agora vamos criar uma empresa de exemplo se não existir
INSERT INTO empresas (
    id,
    razao_social,
    nome_fantasia,
    cnpj,
    inscricao_estadual,
    inscricao_municipal,
    regime_tributario,
    endereco,
    cidade,
    estado,
    cep,
    telefone,
    email,
    site,
    logo_url,
    ativo,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    'Exatta Gestão Contábil Ltda',
    'Exatta Contábil',
    '12.345.678/0001-90',
    '123456789',
    '987654321',
    'Lucro Presumido',
    'Rua das Empresas, 123',
    'São Paulo',
    'SP',
    '01234-567',
    '(11) 1234-5678',
    'contato@exattagestao.com.br',
    'www.exattagestao.com.br',
    NULL,
    TRUE,
    NOW(),
    NOW()
) ON CONFLICT (cnpj) DO NOTHING;

-- Por fim, vamos inserir o usuário na tabela usuarios
INSERT INTO usuarios (
    id,
    nome,
    email,
    telefone,
    cargo,
    role,
    foto_url,
    empresa_id,
    permissoes,
    ativo,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM auth.users WHERE email = 'exattagestaocontabil@gmail.com'),
    'Administrador Exatta',
    'exattagestaocontabil@gmail.com',
    '(11) 1234-5678',
    'Administrador',
    'admin',
    NULL,
    (SELECT id FROM empresas WHERE cnpj = '12.345.678/0001-90'),
    '{"dashboard": true, "lancamentos": true, "contas": true, "plano_contas": true, "centro_custos": true, "fluxo_caixa": true, "relatorios": true, "cadastros": true, "configuracoes": true}',
    TRUE,
    NOW(),
    NOW()
);
